# Generated by Django 5.1.3 on 2026-07-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_categoria_mensagem_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='mensagem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mensagens', to='home.tag'),
        ),
    ]
